

CREATE TABLE IF NOT EXISTS  genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(40) DEFAULT 'unknown'
--    ,
--    film_id BIGINT REFERENCES film (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS  mpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(40) DEFAULT 'unknown'
--    ,
--    film_id BIGINT REFERENCES film (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS  director (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(40) DEFAULT 'unknown'
--    ,
--    film_id BIGINT REFERENCES film (id) ON DELETE NO ACTION
);


--
CREATE TABLE IF NOT EXISTS  users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) DEFAULT 'unknown',
    login varchar(200) NOT NULL,
    email varchar(200) NOT NULL,
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS  friend (
    users_id BIGINT  REFERENCES users (id) ON DELETE NO ACTION,
    friend_id BIGINT REFERENCES users (id) ON DELETE NO ACTION
--    ,
--    film_id BIGINT REFERENCES film (id) ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS  film (
    id BIGINT  GENERATED BY DEFAULT AS IDENTITY,
    name varchar(40) NOT NULL,
    description varchar(200) NOT NULL,
    releasedate date,
    duration integer NOT NULL,
   -- genre_id BIGINT  REFERENCES genre (id) ON DELETE NO ACTION,
    mpa_id BIGINT REFERENCES mpa (id) ON DELETE NO ACTION,
    director_id BIGINT REFERENCES director (id) ON DELETE NO ACTION,
    CONSTRAINT films_pk PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS  likes (
    users_id BIGINT  REFERENCES users (id) ON DELETE NO ACTION,
    film_id BIGINT REFERENCES film (id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS  filmgenre (
     film_id BIGINT  REFERENCES film (id) ON DELETE NO ACTION,
     genre_id BIGINT  REFERENCES genre (id) ON DELETE NO ACTION

--    ,
--    film_id BIGINT REFERENCES film (id) ON DELETE NO ACTION
);